# Generated by Django 3.0.4 on 2020-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('state', models.CharField(choices=[('safe', 'safe'), ('panicked', 'panicked'), ('affected', 'affected')], default='safe', help_text='Current State', max_length=50)),
            ],
        ),
    ]
