# Generated by Django 3.0.4 on 2020-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='division',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('barisal', 'Barisal'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='state',
            field=models.CharField(blank=True, choices=[('safe', 'safe'), ('panicked', 'panicked'), ('affected', 'affected')], max_length=50, null=True),
        ),
    ]
