# Generated by Django 3.0.4 on 2020-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20200322_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
