# Generated by Django 3.0.4 on 2020-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20200326_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bangladesh_result',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='world_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
